package net.groupw.tp_so.Gui;


import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Locale;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import net.groupw.tp_so.Files.*;
import net.groupw.tp_so.Interface.ChatCallback;
import net.groupw.tp_so.Interface.LogCallback;


public class LoginForm extends JFrame {
    private JPanel LoginPanel2;
    private JLabel ImageLogo;
    private JTextField userField;
    private JPasswordField passwordField;
    private JButton loginBtn;

    public LoginForm(Station station) {
        $$$setupUI$$$();
        setContentPane(LoginPanel2);
        setTitle("Login");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(500, 550);
        setLocationRelativeTo(null);
        setVisible(true);

        ImageIcon icon = new ImageIcon("src/main/java/net/groupw/tp_so/assets/logo.png");
        setIconImage(icon.getImage());
        loginBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performLogin(station);
            }
        });
    }


    private void performLogin(Station station) {
        String username = userField.getText();
        String password = new String(passwordField.getPassword());


        Login login = new Login(station);

        User loggedUser = new User();

        // Aqui você colocaria a lógica de verificação do login
        if (login.login(username, password)) {
            JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
            SwingUtilities.invokeLater(() -> {

                if (User.getRole().equals("director")) {
                    new MenuAdmin(loggedUser);

                } else {
                    new Menu(loggedUser);
                }
                dispose();
            });
        } else {
            JOptionPane.showMessageDialog(this, "Falha no login. Tente novamente.");
        }
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here

        ImageLogo = new JLabel(new ImageIcon("src/main/java/net/groupw/tp_so/assets/logo.png"));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        LoginPanel2 = new JPanel();
        LoginPanel2.setLayout(new FormLayout("fill:50px:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:50px:noGrow", "center:d:grow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:30px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:10px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        LoginPanel2.setBackground(new Color(-855310));
        LoginPanel2.setMinimumSize(new Dimension(450, 500));
        LoginPanel2.setPreferredSize(new Dimension(450, 500));
        ImageLogo.setMinimumSize(new Dimension(150, 150));
        ImageLogo.setPreferredSize(new Dimension(150, 150));
        ImageLogo.setText("");
        CellConstraints cc = new CellConstraints();
        LoginPanel2.add(ImageLogo, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer1, cc.xyw(1, 1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer2, cc.xyw(1, 21, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer3, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer4, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Poppins Black", -1, 24, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-16751002));
        label1.setText("LOGIN");
        LoginPanel2.add(label1, cc.xy(3, 7, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-16751002));
        label2.setText("Username");
        LoginPanel2.add(label2, cc.xy(3, 9));
        userField = new JTextField();
        Font userFieldFont = this.$$$getFont$$$("Poppins Medium", -1, 14, userField.getFont());
        if (userFieldFont != null) userField.setFont(userFieldFont);
        userField.setMinimumSize(new Dimension(49, 30));
        userField.setPreferredSize(new Dimension(49, 30));
        LoginPanel2.add(userField, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-16751002));
        label3.setText("Password");
        LoginPanel2.add(label3, cc.xy(3, 13));
        passwordField = new JPasswordField();
        Font passwordFieldFont = this.$$$getFont$$$("Poppins Medium", -1, 14, passwordField.getFont());
        if (passwordFieldFont != null) passwordField.setFont(passwordFieldFont);
        passwordField.setMargin(new Insets(4, 12, 4, 12));
        passwordField.setPreferredSize(new Dimension(49, 30));
        LoginPanel2.add(passwordField, cc.xy(3, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
        loginBtn = new JButton();
        loginBtn.setBackground(new Color(-16751002));
        loginBtn.setBorderPainted(false);
        Font loginBtnFont = this.$$$getFont$$$("Poppins Black", -1, 16, loginBtn.getFont());
        if (loginBtnFont != null) loginBtn.setFont(loginBtnFont);
        loginBtn.setForeground(new Color(-1));
        loginBtn.setLabel("Login");
        loginBtn.setPreferredSize(new Dimension(130, 50));
        loginBtn.setText("Login");
        LoginPanel2.add(loginBtn, cc.xy(3, 19, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer5, cc.xy(3, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
        LoginPanel2.add(spacer6, cc.xy(3, 17, CellConstraints.DEFAULT, CellConstraints.FILL));
        label2.setLabelFor(userField);
        label3.setLabelFor(passwordField);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoginPanel2;
    }
}
