package net.groupw.tp_so.Gui;


import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import net.groupw.tp_so.Files.*;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class Profile extends JFrame {
    private JPanel ProfilePanel;
    private JLabel Profile;
    private JLabel Nome;
    private JLabel Cargo;
    private JLabel CampoNome;
    private JLabel CampoCargo;
    private JPanel CargoPanel;
    private JPanel NomePanel;
    private JLabel Logo;

    public Profile(User user) {
        $$$setupUI$$$();
        setContentPane(ProfilePanel);
        setTitle("Profile");
        setSize(400, 400);
        setLocationRelativeTo(null);
        setVisible(true);

        ImageIcon icon = new ImageIcon("src/main/java/net/groupw/tp_so/assets/logo.png");
        setIconImage(icon.getImage());

        CampoNome.setText(user.getUsername());

        System.out.println("PROFILE : " + user.getUsername());

        CampoCargo.setText(user.getRole());

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        Logo = new JLabel(new ImageIcon("src/main/java/net/groupw/tp_so/assets/logo.png"));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        ProfilePanel = new JPanel();
        ProfilePanel.setLayout(new FormLayout("fill:30px:noGrow,left:4dlu:noGrow,fill:50px:grow,left:4dlu:noGrow,fill:30px:noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        ProfilePanel.setBackground(new Color(-855310));
        ProfilePanel.setPreferredSize(new Dimension(400, 400));
        Profile = new JLabel();
        Font ProfileFont = this.$$$getFont$$$("Roboto Light", Font.BOLD, 24, Profile.getFont());
        if (ProfileFont != null) Profile.setFont(ProfileFont);
        Profile.setForeground(new Color(-16751002));
        Profile.setText("Profile");
        CellConstraints cc = new CellConstraints();
        ProfilePanel.add(Profile, cc.xy(3, 5, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        ProfilePanel.add(spacer1, cc.xy(3, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        ProfilePanel.add(spacer2, cc.xy(3, 11, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        ProfilePanel.add(spacer3, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        ProfilePanel.add(spacer4, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        NomePanel = new JPanel();
        NomePanel.setLayout(new BorderLayout(0, 0));
        NomePanel.setBackground(new Color(-855310));
        ProfilePanel.add(NomePanel, cc.xy(3, 7));
        Nome = new JLabel();
        Nome.setBackground(new Color(-13947600));
        Nome.setForeground(new Color(-16751002));
        Nome.setText("Name         ");
        NomePanel.add(Nome, BorderLayout.WEST);
        CampoNome = new JLabel();
        CampoNome.setBackground(new Color(-13947600));
        CampoNome.setForeground(new Color(-14540254));
        CampoNome.setText("Label");
        NomePanel.add(CampoNome, BorderLayout.CENTER);
        CargoPanel = new JPanel();
        CargoPanel.setLayout(new BorderLayout(0, 0));
        CargoPanel.setBackground(new Color(-855310));
        ProfilePanel.add(CargoPanel, cc.xy(3, 9));
        Cargo = new JLabel();
        Cargo.setForeground(new Color(-16751002));
        Cargo.setText("Role           ");
        CargoPanel.add(Cargo, BorderLayout.WEST);
        CampoCargo = new JLabel();
        CampoCargo.setText("Label");
        CargoPanel.add(CampoCargo, BorderLayout.CENTER);
        Logo.setPreferredSize(new Dimension(150, 150));
        Logo.setText("");
        ProfilePanel.add(Logo, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ProfilePanel;
    }
}
